### ISSUE TITLE
README

### ISSUE THREAD

**Issue by crutchcorn** [artemanufrij/playmymusic#1]
It would be nice to have a README that has installation instructions, screenshots, and more information on the project

**Comment by artemanufrij** [comment]
@crutchcorn I've added a README file:
https://github.com/artemanufrij/playmymusic/blob/master/README.md

**Comment by crutchcorn** [comment]
You mistakenly refered to this project as Regextester in the README. Might be something you wanna fix

**Comment by artemanufrij** [comment]
@crutchcorn done :)
