### ISSUE TITLE
Rescan library while playing breaks the app

### ISSUE THREAD

**Issue by WebShapedBiz** [artemanufrij/playmymusic#10]
On Rescan Library while playing the app exits immediately. After restart there is no songs in library and automatic scan begins like on the first run.

**Comment by artemanufrij** [comment]
hm... I tested this use case again and again on three systems... Can you reproduce it?

**Comment by WebShapedBiz** [comment]
It is happening on every rescan. The last time, just minute ago, with new behaviour.
On previous occasions, after restart, there are no songs in the library and automatic scan restored them as they were before. However, the last time the rescan split my album the was playing and created two entries in my library - one with only one song, the one that was plaing, and all the other songs were put in "second" album.
I'm using vanilla Elementary OS but not 0.4.1., the "old" one with all updates but without HWE kernel,
Linux 4.4.0-96-generic

**Comment by WebShapedBiz** [comment]
Result: https://www.useloom.com/share/bf7512ead7f74a33bd93e1fd4647de4a

**Comment by artemanufrij** [comment]
could you start the player from console by `com.github.artemanufrij.playmymusic` and reproduce this crash please?

**Comment by WebShapedBiz** [comment]
Already did. There is no error messages while rescanning/exiting but there is an error message always at start of app: 

> [INFO 20:55:00.507751] Application.vala:153: Play My Music version: (null)
[INFO 20:55:00.507782] Application.vala:155: Kernel version: 4.4.0-96-generic
[WARNING 20:55:00.518164] Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-1MOOUInRZr: Veza odbijena

**Comment by artemanufrij** [comment]
Currently I'm testing it on tree systems with 100 - 5500 files. It runs very stable. :confused: 

```
[INFO 21:01:22.012553] Application.vala:153: Play My Music version: (null)
[INFO 21:01:22.012575] Application.vala:155: Kernel version: 4.10.0-35-generic
```

**Comment by WebShapedBiz** [comment]
I have another computer (Elementary OS with HWE kerel) so I could try there if you think it would help you.

**Comment by artemanufrij** [comment]
It would be very helpful!

**Comment by WebShapedBiz** [comment]
On my laptop It works flawlessly.

**Comment by artemanufrij** [comment]
That's what I mean...

**Comment by WebShapedBiz** [comment]
So the conclusion is what? I'm should listen a better music on my desktop? ;-)

**Comment by artemanufrij** [comment]
which vala version is installed on your systems? `vala --version`

**Comment by WebShapedBiz** [comment]
Apparently none, it said that I should apt install valac. But I have no other issues with my system.

**Comment by WebShapedBiz** [comment]
Desktop/Laptop: libvala 0.36.5

**Comment by artemanufrij** [comment]
I'm going to close this issue... I guess I can't fix it for "old" kernel... thank you for your support!
