### ISSUE TITLE
Default Album and Artist artwork for unknown metadata

### ISSUE THREAD

**Issue by SubhadeepJasu** [artemanufrij/playmymusic#101]
Currently the app assigns a random album and artist image for unknown album or artist or for songs which it couldn't gather data about. It would be better to assign a default album image (like a staff note or an audio cd icon) and a default avatar for artist.
![image](https://user-images.githubusercontent.com/20795161/38148710-37b56632-3475-11e8-9b21-7be58adca6a0.png)
As you see in the image that the album art for Above & Beyond and artist image of Owl City is being shown by default for Heart Attack (originally by Demi Lavato). This becomes annoying at times when I want to listen to A&B and I click on one and find out that its a different song.

**Comment by artemanufrij** [comment]
hey @SubhadeepJasu thanks for feedback. You can change album art by right click in "album view"...

**Comment by SubhadeepJasu** [comment]
Yeah but doing that has this problem. #88 which prevents me from editing metadata of specific songs.

**Comment by SubhadeepJasu** [comment]
Basically all the songs which don't have a proper metadata, are given a common album and a common artist which is me.  Since there is no way to change album of a specific song, editing album name from album view will set all the same album name for all the songs. For example I wanna change album of heart attack. In album view all those songs without metadata have the same album "music". So changing the name of "music" to say "lavato hits" would also change the album name of all the songs which were assigned the same album. The same goes for artist name. In order to fix this problem i have a potential solution in #88

**Comment by SubhadeepJasu** [comment]
This has been fixed.
