### ISSUE TITLE
Danish translation file

### ISSUE THREAD

**Issue by rasmus91** [artemanufrij/playmymusic#102]
Here's a file with a danish po file. Please note that as certain words are troublesome to translate as there's either the direct translation or the contextual one, and at times it can be hard to decide which is more correct to use; The case I'm speaking of in particular is 'Tracks in Album' being best translated to 'Numre i Album', however, at some other place, where it is just 'track', 'Spor' is a better translation as the other one would have the same meaning as 'number' in this case, or at least be readily construed to have this. Otherwise, the file should be complete 

[da.po.zip](https://github.com/artemanufrij/playmymusic/files/1872562/da.po.zip)

**Comment by artemanufrij** [comment]
thank you @rasmus91! I added your translation file into current master branch. The Translation will be available with next release!

**Comment by rasmus91** [comment]
I can't help but notice that the titles aren't translated though the file is complete i believe. Can translation options be added for those? (see attached image)
![gettunes](https://user-images.githubusercontent.com/2297739/38355472-47d419f4-38bd-11e8-9755-1de02d029add.png)
![getradio](https://user-images.githubusercontent.com/2297739/38355473-47f1f8a2-38bd-11e8-862e-bbaa75ea5ee8.png)

**Comment by artemanufrij** [comment]
hey @rasmus91 I updated the pot/po content. Coult you test it please?

**Comment by rasmus91** [comment]
There's the updated file right back. and i saw you put 'rasmus91' in that xml file. You may replace it with 'Rasmus Lindegaard'

[da.po.zip](https://github.com/artemanufrij/playmymusic/files/1881283/da.po.zip)

**Comment by rasmus91** [comment]
I got around to actually getting the build working here, and though a lot of new text is translated, there's still a couple of things missing from the file. For all the menus, the title in the middle is still in english.  (including radio, which isn't shown here). The tooltip for tracks is also still in english.

![tracks](https://user-images.githubusercontent.com/2297739/38391063-76548f00-3923-11e8-9921-caa909b31edc.png)

![artists](https://user-images.githubusercontent.com/2297739/38391077-7ea690c2-3923-11e8-91f0-cc4f2d92f453.png)

![playlists](https://user-images.githubusercontent.com/2297739/38391064-7671ef50-3923-11e8-9050-f11ca89102a6.png)
