### ISSUE TITLE
Add "Copy to collection" option on import

### ISSUE THREAD

**Issue by it-s** [artemanufrij/playmymusic#107]
Currently when importing files in Melody, the files are not moved. They are simply added to the database. It would be nice to have an option to actually copy/move the files into the music library folder. And as a bonus to place the files into "/[artist]/[album]/" folder (like iTunes does).

**Comment by artemanufrij** [comment]
hey @it-s could you test current master branch please? I added a new option into Preferences dialog
![bildschirmfoto von 2018-04-15 18 51 44](https://user-images.githubusercontent.com/16517095/38780932-127c7c14-40de-11e8-99bb-836864f2eb99.png)

**Comment by it-s** [comment]
Works like a charm! Thanks.

**Comment by artemanufrij** [comment]
@it-s thanks for your feedback
