### ISSUE TITLE
Melody "Hanging"

### ISSUE THREAD

**Issue by Jimthetyreman** [artemanufrij/playmymusic#118]
![melody screenshot from 2018-06-28 16 29 24](https://user-images.githubusercontent.com/18515872/42044422-e1f11f8a-7af0-11e8-88b3-6244c12cf52d.jpeg)
Melody just hangs and freezes "Loading... Reading out database content"

**Comment by Jimthetyreman** [comment]
Artem,

Thanks for getting back to me so quickly, I've currently got in excess of 58,000 files in my music folder.
Jim.

**Comment by artemanufrij** [comment]
@Jimthetyreman I improved initial loading. could you test current master branch please?
