### ISSUE TITLE
Suggestion: Work with the default music app

### ISSUE THREAD

**Issue by yeboahnanaosei** [artemanufrij/playmymusic#12]
Hi, thanks for such a great music app. I've been using elementary's default music app and I do enjoy it.
However things like album art has never worked. With your app, album art works perfectly. I would like to suggest that instead of creating a different app, why not work on the default music app and implement some of the things you've implemented in this app. I think the elementary world will benefit greatly from this. I might be completely wrong, but I feel your app is even a fork of the main app right?

**Comment by artemanufrij** [comment]
Hi @yeboahnanaosei , thank you for your suggestion.

As first I tried to fix it in Noise. But it was a very big challenge. That was one of any reasons why it started a new app **from scratch**.
