### ISSUE TITLE
Background playing support

### ISSUE THREAD

**Issue by png2378** [artemanufrij/playmymusic#13]
It would be cool.

**Comment by J0Ar** [comment]
Yes, this is a needed feature. I think this has some relation to #6 ... MPRIS support :)

**Comment by artemanufrij** [comment]
hey @png2378 @J0Ar could you test current master branch please?
![pref](https://user-images.githubusercontent.com/16517095/31406746-c1294b80-ae02-11e7-88b1-e1fd6b2fd9e2.png)

**Comment by worldofpeace** [comment]
Hey @artemanufrij  I tested it. Seems to work. :)

**Comment by artemanufrij** [comment]
release is waiting for human testing... [AppCenter]

**Comment by png2378** [comment]
@artemanufrij works well for me, ty!
