### ISSUE TITLE
Sound indicator shows melody as not playing, despite playing music

### ISSUE THREAD

**Issue by yerbestpal** [artemanufrij/playmymusic#140]
![screenshot from 2018-10-19 11-04-23](https://user-images.githubusercontent.com/15250241/47212070-1c193c00-d38f-11e8-8980-ccdbd0eb1e62.png)

**Comment by artemanufrij** [comment]
@yerbestpal thanks for feedback I will check it as soon as possible!

**Comment by artemanufrij** [comment]
@yerbestpal I can't reproduce it on my system:
![screenshot von 2018-10-19 13 35 33](https://user-images.githubusercontent.com/16517095/47216050-f21e4480-d3a3-11e8-8bfa-9141dbc23fea.png)

**Comment by yerbestpal** [comment]
Strange. Are you using Juno?

**Comment by artemanufrij** [comment]
yes

**Comment by artemanufrij** [comment]
![screenshot von 2018-10-19 13 40 51](https://user-images.githubusercontent.com/16517095/47216259-9f915800-d3a4-11e8-9ab6-3d989bc9edd1.png)

**Comment by yerbestpal** [comment]
Hrm. Unfortunately I am not a developer so I am very limited as far as diagnosing any issues is concerned.

**Comment by artemanufrij** [comment]
@yerbestpal no problem. What happens if you use the buttons inside the widget?

**Comment by yerbestpal** [comment]
Okay, I can no longer reproduce the bug.

**Comment by artemanufrij** [comment]
Can I close this issue?

**Comment by yerbestpal** [comment]
I think so. If it occurs again I'll be sure to mention.
