### ISSUE TITLE
Please add option to switch chosen columns on/off and re-arrange them

### ISSUE THREAD

**Issue by DanyGee** [artemanufrij/playmymusic#144]
Hi,
the program is very promising.
It would be nice to have an option to disable columns of choice and rearrange them too.
For example I totally don't care about the track number, yet I cannot disable it in the view.

**Comment by artemanufrij** [comment]
@DanyGee you can test switching columns on/off:

![screenshot von 2018-10-23 01 13 18](https://user-images.githubusercontent.com/16517095/47324701-3db14680-d661-11e8-8194-e43ec4f55d80.png)

resort will coming soon...

**Comment by DanyGee** [comment]
Wow, nice building from sources experience. Clear instructions and no errors on building :tada: 
Hiding the columns became visible, and works as expected - BIG THX!
For test purposes, I disabled all columns. Now I cannot make them visible again :scream:

**Comment by DanyGee** [comment]
Had good experience building it from source code - clear instructions and no errors on build :+1: 
`Columns Visibility` option became visible and works as expected :tada: 
For test purposes I disabled all columns. With right-click I couldn't re-enable them, so I went `options->reset all views`. At program relaunch the columns were still missing, most probably because of re-syncing the database from scratch, which took a while. After relaunching Melody again, default columns came back.
You may consider an option to re-enable columns under right-click menu, once they all have been disabled - may save you a couple of bug report duplicates :wink:

**Comment by artemanufrij** [comment]
@DanyGee could you test it again please? A added a message if you try to hide last column:
![screenshot von 2018-10-23 19 51 44](https://user-images.githubusercontent.com/16517095/47380268-53744980-d6fd-11e8-8fe6-1c0cd7217f87.png)

**Comment by DanyGee** [comment]
Nice, works as expected - won't let me hide last column :+1:

**Comment by artemanufrij** [comment]
@DanyGee thank you for testing. I'm going to close this issue and open a new one "reorder columns"...
