### ISSUE TITLE
German translation not displayed

### ISSUE THREAD

**Issue by riker09** [artemanufrij/playmymusic#150]
I installed the latest update this morning and came across a glitch. In the settings dialogue the translation for `Remove Playlist if last Track was removed` is not shown in German but in English (last setting).

![playmymusic - german translation](https://user-images.githubusercontent.com/568497/47637659-b8e09400-db5c-11e8-8102-14aedb0132c9.png)

What is weird about this: The translation is there in the `de.pot` file.

**Comment by artemanufrij** [comment]
@riker09 I translated it few days ago. It's not released, yet.

**Comment by riker09** [comment]
Ah, okay. I see. Nevermind then. :smiley:
