### ISSUE TITLE
Load Album Artwork from file metadata

### ISSUE THREAD

**Issue by SubhadeepJasu** [artemanufrij/playmymusic#155]
In case the user haven't applied a custom album artwork for a song in Melody, use artwork from file if available.

**Comment by artemanufrij** [comment]
it does already. here are the possible files:
['cover.jpg', 'Cover.jpg', 'cover.png', 'Cover.png', 'album.jpg', 'Album.jpg', 'album.png', 'Album.png', 'folder.jpg', 'Folder.jpg', 'folder.png', 'Folder.png', 'front.jpg', 'Front.jpg', 'front.png', 'Front.png']

**Comment by SubhadeepJasu** [comment]
Ok'ill check once again.

**Comment by artemanufrij** [comment]
Could you check it?

**Comment by SubhadeepJasu** [comment]
Ok, I checked it and yeah it works. Sorry for the false issue. Looks like it was an issue with clementine which I used to write the cover art in the mp3.
