### ISSUE TITLE
Jump to current playing song / album

### ISSUE THREAD

**Issue by dmanlfc** [artemanufrij/playmymusic#16]
It would be great to have an album art next to the player controls on the app window that you can click on. This will then take you to that song / album / artist in the current view.

**Comment by artemanufrij** [comment]
Click into header bar for jumping into curren album:
![header ba](https://user-images.githubusercontent.com/16517095/31407350-ecbe4dde-ae04-11e7-8930-133677e5185c.png)

**Comment by dmanlfc** [comment]
Hi Artem,

Tested - yes it works for 'Albums' view but not Artists view.
It would be great if the current album/song art was in the header bar also.

Good work on the other stuff!
- Sound Indicator works fine - although I'm not a fan of having to hit the previous track button twice.
-- It's a bit clunky as the indicator size is dynamic - therefore the controller buttons are sometimes positioned differently.
- Playing in the background works too - niiiice

Roll on playlists! :-)

Dan

**Comment by artemanufrij** [comment]
@dmanlfc on click the bar it jumps to the playing track. If you start it from "Album"-view - it jumps into album. If from "Artist"-View - it jumps into artist.

**Comment by dmanlfc** [comment]
Yeah - confirmed.
If possible it would be good that it jumps to the current open view, not necessarily the view you started with?

**Comment by artemanufrij** [comment]
Maybe it makes sense to implement a feature like: 
Go To ->
-> Album
-> Artist

but let open a separate issue.
