### ISSUE TITLE
DB coding issue?

### ISSUE THREAD

**Issue by dmanlfc** [artemanufrij/playmymusic#17]
If Album Titles or Artists have an "&" in their name they're shown as "&amp"
Funnily enough if you hover over the Album it shows correctly

**Comment by artemanufrij** [comment]
Could you post a screenshot, please?

**Comment by dmanlfc** [comment]
![screenshot from music](https://user-images.githubusercontent.com/32564392/31276480-69176664-aadf-11e7-8da8-0eebf331b96c.png)

**Comment by artemanufrij** [comment]
Thank you! I will fix it tonight

**Comment by artemanufrij** [comment]
Current master branch solve the issue... could you test it please?

**Comment by dmanlfc** [comment]
Yes fixed - thanks!

**Comment by artemanufrij** [comment]
Thank you for your support!
