### ISSUE TITLE
Symbolic links in library folder not working

### ISSUE THREAD

**Issue by jtrees** [artemanufrij/playmymusic#18]
### Steps to Reproduce
1. Create a folder `~/foo`
2. Create a symbolic link pointing to a folder that contains music at `~/foo/bar`
3. Select "Change Music Folder..." from the menu in the app

### Expected Result
The music pointed to by the symbolic link `bar` should turn up in the library.

### Actual Result
The music is not added to the library. Rescanning does not help.

**Comment by artemanufrij** [comment]
HEy @jtrees, current master branch should fix this issue. Could you test it please?

**Comment by jtrees** [comment]
It works! Wow, that response speed was epic! :+1:
