### ISSUE TITLE
An auto timed Now Playing window.

### ISSUE THREAD

**Issue by SubhadeepJasu** [artemanufrij/playmymusic#19]
A minimal Now Playing window when the player is not in use for some time but is playing music. Basic controls in the now playing window. And also a Now Playing button or clicking on the song title above should take to the Now Playing screen.

**Comment by artemanufrij** [comment]
do you mean something like #6 ?

**Comment by SubhadeepJasu** [comment]
Nope, its about a dedicated Now Playing screen.

**Comment by SubhadeepJasu** [comment]
A few examples :

![image](https://user-images.githubusercontent.com/20795161/31351996-c0ba5698-ad4a-11e7-9c21-e710c5b84f25.png)
![image](https://user-images.githubusercontent.com/20795161/31352020-d3ad6f60-ad4a-11e7-9d34-4e2340edf839.png)
![image](https://user-images.githubusercontent.com/20795161/31352100-18e6c022-ad4b-11e7-8cd8-d9b78752c2dc.png)
![image](https://user-images.githubusercontent.com/20795161/31352145-42643f10-ad4b-11e7-865f-c3facb0f069c.png)
In now playing mode the player switches to a minimal UI with basic controls. It can be swtched to now playing mode manually or automatically after some time. The now playing screen has a switch to full mode button for switching back to usual UI.

**Comment by artemanufrij** [comment]
Sound indicator:
![bildschirmfoto von 2017-10-09 20 25 22](https://user-images.githubusercontent.com/16517095/31352706-09a8cf26-ad30-11e7-9396-5cd0dab28822.png)

Desktop notification, if window is inactive:
![unbenannt](https://user-images.githubusercontent.com/16517095/31352165-08afbd66-ad2e-11e7-918c-58a9c9d984db.png)

**Comment by SubhadeepJasu** [comment]
A now playing window is different from a sound indicator. Its a different thing. See the above images.

**Comment by artemanufrij** [comment]
I don't plan to implement a separate window.
