### ISSUE TITLE
Update GNOME runtime

### ISSUE THREAD

**Issue by haggen88** [artemanufrij/playmymusic#193]
Updating flatpak I found the following message:

Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.artemanufrij.playmymusic

Btw ..  great app!!!

**Comment by vchernin** [comment]
This is solved now thanks to https://github.com/flathub/com.github.artemanufrij.playmymusic/pull/12.
