### ISSUE TITLE
Missing dependency > No package 'libsoup-2.4' found

### ISSUE THREAD

**Issue by J0Ar** [artemanufrij/playmymusic#2]
On a standard elementaryOS installation there is a missing package called `libsoup-2.4`
I did a `sudo apt install libsoup*` and everything went fine. 
Maybe this was too much but there are so many libsoup-packages around :D

Error message:
![bildschirmfoto von 2017-09-28 13 16 46](https://user-images.githubusercontent.com/23266409/30963871-6fbf1368-a44f-11e7-8c71-9127afcf0b53.png)
Solved:
![bildschirmfoto von 2017-09-28 13 17 34](https://user-images.githubusercontent.com/23266409/30963889-821a5c52-a44f-11e7-9492-03ac1e3941e8.png)

**Comment by artemanufrij** [comment]
@J0Ar thank you for your feedback.
`sudo apt install libsoup2.4-dev` should be installed.

PS: I updated README.MD already
