### ISSUE TITLE
Add support for changing song information

### ISSUE THREAD

**Issue by SubhadeepJasu** [artemanufrij/playmymusic#22]
Add support for changing song meta data with or without changing ID3 tags.

**Comment by dmanlfc** [comment]
Yes please - ideally ID3 so other software can benefit in the future.
I'd like to be able to right click - 'Update Tag Information' then adjust accordingly.
This should update the back-end database & be reflected in the GUI immediately.
Currently you have to re-scan the library.

**Comment by artemanufrij** [comment]
currently you can change Album information [F2] or Artist information [F2]. If you activate "Save changes into ID3-Tag" so player does it.

https://plus.google.com/101587650787796657209/posts/YRFBd88xwu8

**Comment by SubhadeepJasu** [comment]
Yep :) Thanks. This issue has been solved.
