### ISSUE TITLE
Music on GVFS mounted samba share not found

### ISSUE THREAD

**Issue by theoriginalbigbaddave** [artemanufrij/playmymusic#29]
**What I'm trying to do:**

Set my music folder to a folder on a samba share on my NAS.
Mounted via GVFS using files (under `/run/user/<UID>/gvfs/`).

**Expected result:**

Music files in the target folder are indexed by Music Player.

**What happens:**

No music files are indexed.

**Additional Info:**

There is no output to the terminal when running from there and adding the folder or rescanning the library.

The correct path is stored under the **library-location** dconf key.

When copying a subset of the music files from the share to a folder on the local drive and setting the folder as my music folder the files are indexed sucessfully.

**Comment by artemanufrij** [comment]
@theoriginalbigbaddave thanks for  feedback. I will check it next days

**Comment by artemanufrij** [comment]
@theoriginalbigbaddave could you test current master branch please? I moved from `path` to `uri`. now it should work.

**Comment by theoriginalbigbaddave** [comment]
No joy with building from master, same behaviour as previously.

No warnings / errors posted to terminal when adding the the root of my music collection as the library folder, no files indexed.

However if I set a folder that contains music files (as opposed to subfolders of music files) as the library path, the following warnings are generated;

```
** (com.github.artemanufrij.playmymusic:28643): WARNING **: TagManager.vala:63: DISCOVER ERROR: '5' "/run/user/1000/gvfs/smb-share:domain=WORKGROUP,server=borovitskaya,share=users,user=dave/dave/Music/Arctic Monkeys/Favourite Worst Nightmare/" is a directory. GST_DISCOVERER_ERROR
(file:///run/user/1000/gvfs/smb-share:domain=WORKGROUP,server=borovitskaya,share=users,user=dave/dave/Music/Arctic%20Monkeys/Favourite%20Worst%20Nightmare/)

** (com.github.artemanufrij.playmymusic:28643): WARNING **: TagManager.vala:63: DISCOVER ERROR: '5' Could not open resource for reading. GST_DISCOVERER_ERROR
(smb://WORKGROUP;dave@borovitskaya/users/dave/Music/Arctic%20Monkeys/Favourite%20Worst%20Nightmare/)
```

the same number of warnings are generated as there are music files in the folder.

**Comment by theoriginalbigbaddave** [comment]
Oops.

**Comment by theoriginalbigbaddave** [comment]
Built from master again today, its fixed nice one.

**Comment by artemanufrij** [comment]
@theoriginalbigbaddave thank you for feedback. I'm going to close this issue.
