### ISSUE TITLE
Some Radiostreams doesn't work and the UI freeze

### ISSUE THREAD

**Issue by J0Ar** [artemanufrij/playmymusic#3]
I tested several webstations i mostly listen to and there are some which doesn't work...also when you select such an stream the the app freezes...

_http://www.antenne.de/webradio/channels/chillout.m3u_
_http://www.etn.fm:8200/house-mp3-320_
_http://streams.rsa-sachsen.de/rsa-live/aac-64/mediaplayerrsa_

**Comment by artemanufrij** [comment]
@J0Ar could you text current master branch please?

**Comment by J0Ar** [comment]
Ha...now the streams working fine and they load really fast...great. Also the flowbox? design is much better.

**Comment by artemanufrij** [comment]
@J0Ar thank you for your feedback! I'm going to close this issue.

**Comment by cristianmos** [comment]
I have the latest app update. I can play http://stream2.srr.ro:8022, but I can't play http://stream.radiozu.ro:8020 and UI freezes. If I chnage it to http://stream1.radiozu.ro:8020, which is a wrong address, but with a number after "stream", it doesn't play anything, but it doesn't freeze anymore.

**Comment by artemanufrij** [comment]
@cristianmos Thank you for your feedback. I will test it tonight...

**Comment by artemanufrij** [comment]
@cristianmos I fixed it. I will shipp new release next days.

**Comment by cristianmos** [comment]
@artemanufrij It works fine now. Thanks!

**Comment by artemanufrij** [comment]
@cristianmos you are welcome
