### ISSUE TITLE
current master (c27855d) fails to build 

### ISSUE THREAD

**Issue by worldofpeace** [artemanufrij/playmymusic#30]
During compilation I get this error:

.../playmymusic/src/Widgets/TrackTimeLine.vala:34.9-34.23: error: The type name `Granite.SeekBar' could not be found
        Granite.SeekBar timeline;
        ^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 86 warning(s)
src/CMakeFiles/com.github.artemanufrij.playmymusic.dir/build.make:196: recipe for target 'src/com.github.artemanufrij.playmymusic_valac.stamp' failed
make[2]: *** [src/com.github.artemanufrij.playmymusic_valac.stamp] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/com.github.artemanufrij.playmymusic.dir/all' failed
make[1]: *** [src/CMakeFiles/com.github.artemanufrij.playmymusic.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by artemanufrij** [comment]
@worldofpeace you need last master brunch of Granite. Seek bar will be shipped next days.

**Comment by worldofpeace** [comment]
Yay new stuff! I'll close this in that case.
