### ISSUE TITLE
Capabilities request: Dynamically update Tag info to DB

### ISSUE THREAD

**Issue by dmanlfc** [artemanufrij/playmymusic#35]
Hi @artemanufrij 

I've noticed some inconsistencies with song tagging in my Library which I'm slowly tidying up.
i.e. Lady GaGa vs Lady Gaga or Guns 'N' Roses vs Guns N' Roses.
(Don't judge me, this is a shared Music library unfortunately :-) )

If you change / fix some tags (i.e. using MusicBrainz Picard) after the initial DB import the old tags are still shown in PlayMyMusic.
It would be great if your app automatically updated the tags to the DB in this scenario & removed older references.
This goes the same for Files that have been renamed.

Maybe changing what 'Rescan Library' does - Just to update & remove orphans rather than clear & update.

Something to think about...

Dan

**Comment by artemanufrij** [comment]
In case of " Lady GaGa vs Lady Gaga": I could ignore lower and upper cases for checking artist name. It would be easy to fix.

**Comment by dmanlfc** [comment]
@artemanufrij that won't fix the ability to update the DB.
I had a quick look through the code. The 'Rescan Library' option is misleading.
- Rescan should do exactly that & not drop the DB but you actually 'Reset it'
- Currently it resets the view & DB via reset_all_views (); & db_manager.reset_database ();

Ideally those calls should be avoided & then we probably need some methods to 'update' & 'dispose' (in the event the filename is different) the DB tags that already exist via LibraryManager.vala.

**Comment by artemanufrij** [comment]
An option like `Sync`? No problem...

**Comment by dmanlfc** [comment]
Sync, Re-Sync, Refresh - just not Reset :-)

**Comment by artemanufrij** [comment]
@dmanlfc I changed it. Now it will resync library. It means: add new music files into library and remove all non exists items from library. could you test it?

**Comment by dmanlfc** [comment]
@artemanufrij unfortunately it crashes...

** (com.github.artemanufrij.playmymusic:11744): WARNING **: TagManager.vala:63: DISCOVER ERROR: '3' Resource not found. GST_DISCOVERER_ERROR
(file:///home/dman/Music/Destinys Child - #1's/03 - Survivor.mp3)

** (com.github.artemanufrij.playmymusic:11744): WARNING **: TagManager.vala:63: DISCOVER ERROR: '3' Resource not found. GST_DISCOVERER_ERROR
(file:///home/dman/Music/Destinys Child - #1's/05 - Check On It (Beyonce ft.Slim Thug).mp3)
Segmentation fault (core dumped)

**Comment by artemanufrij** [comment]
fixed crash on url's with a #
