### ISSUE TITLE
Not Showing all songs in Album View

### ISSUE THREAD

**Issue by arshubham** [artemanufrij/playmymusic#37]
Steps to Reproduce:
1. Copy Songs to ~/Music/Folder/
2. Start Music Player
3. Applications Scans for Music
![screenshot from 2017-11-05 21 10 07](https://user-images.githubusercontent.com/14235191/32416414-b11eb51a-c26e-11e7-838e-23a82bca76fa.png)
4. Only 2 Songs out of 4 are shown.
![screenshot from 2017-11-05 21 10 19](https://user-images.githubusercontent.com/14235191/32416422-cf7f6fcc-c26e-11e7-9746-9b25bbacd80c.png)
5. Rescan the Library.
![screenshot from 2017-11-05 21 10 38](https://user-images.githubusercontent.com/14235191/32416428-e5e6c7d8-c26e-11e7-8dd9-156d554ea776.png)
6. Now only 3 out of 4 are shown.
![screenshot from 2017-11-05 21 10 44](https://user-images.githubusercontent.com/14235191/32416433-f343f57c-c26e-11e7-9d5f-6c70c6d852ae.png)
7. On re-scanning again and again. The number of songs shown alternates between 2 to 4.
![screenshot from 2017-11-05 21 11 46](https://user-images.githubusercontent.com/14235191/32416444-21ae6f32-c26f-11e7-89ca-925ec210ea65.png)

**Note:** Correct Number of songs are shown in Artist view at all times

**Comment by artemanufrij** [comment]
@arshubham is your directory mounted or not? are they .mp3 files?

**Comment by arshubham** [comment]
@artemanufrij The music is in the default Music folder and all the files are .m4a. If needed I can provide the files too.

**Comment by artemanufrij** [comment]
@arshubham I found the bug... give me 10 minutes :smile:

**Comment by artemanufrij** [comment]
@arshubham could you check it again please? (current master branch)

**Comment by arshubham** [comment]
@artemanufrij Works as Expected. Thanks.

**Comment by artemanufrij** [comment]
@arshubham thank you for your support!
