### ISSUE TITLE
Make already existing webradio entries editable

### ISSUE THREAD

**Issue by J0Ar** [artemanufrij/playmymusic#4]
Would be nice if you could edit a webradio entry, which is already in the list.

**Comment by artemanufrij** [comment]
Hey @J0Ar, could you test current master branch, please?

![bildschirmfoto von 2017-10-05 22 20 43](https://user-images.githubusercontent.com/16517095/31250709-00c48380-aa1c-11e7-91f3-08fab3b241d1.png)
