### ISSUE TITLE
Radio and Playlist views are confusing.

### ISSUE THREAD

**Issue by worldofpeace** [artemanufrij/playmymusic#43]
The words "Get Some Tunes" meaning gets confused when used this often.
You really only should "Get Some Tunes" when you first start the app.
In the playlist view I doesn't even say anything about adding music below it.
It reads as "for manage your favorite songs".
![image](https://user-images.githubusercontent.com/28888242/32577921-65d8a3c6-c4a9-11e7-9ba2-96946a890c09.png)
In the radio station view you're techincally adding music. But it still looks confusing.
![image](https://user-images.githubusercontent.com/28888242/32577936-72ee967e-c4a9-11e7-9fb8-47f5eb922e8f.png)

**Comment by worldofpeace** [comment]
Perhaps in the playlist view it says "No Playlists"

**Comment by artemanufrij** [comment]
@worldofpeace Better?

![bildschirmfoto von 2017-11-18 11 43 36](https://user-images.githubusercontent.com/16517095/32979452-c340dcf0-cc55-11e7-8eec-e0fa71a90f4e.png)
![bildschirmfoto von 2017-11-18 11 43 25](https://user-images.githubusercontent.com/16517095/32979453-c388a170-cc55-11e7-93d1-7c004ef9821b.png)

**Comment by worldofpeace** [comment]
@artemanufrij Yes! :)
I was just about to make a pr. Then I saw this.

**Comment by worldofpeace** [comment]
Fixed on master from these commits: https://github.com/artemanufrij/playmymusic/commit/9e3a7d6628712d8176f511eac4f170e2ce911d4c#diff-69b0fbd71b603795ea4c46ff5059658f https://github.com/artemanufrij/playmymusic/commit/9e3a7d6628712d8176f511eac4f170e2ce911d4c#diff-e98682039ded6cec91f3840778ca65ef
