### ISSUE TITLE
Song list view

### ISSUE THREAD

**Issue by yeboahnanaosei** [artemanufrij/playmymusic#44]
Can we have a song list view? Sometimes I want to see a list of all the songs I have in either ascending or descending alphabetical order. I can't seem to do that

**Comment by SubhadeepJasu** [comment]
We need a song list view, its one of the basic views but one of the most useful too. I would like to play all the songs in my library with a click of the play button, or directly go to the song and play it and make it play all the songs in the library. The now playing window I talked about in an earlier version acts as a playlist view too in most music players. It make viewing and managing playlists easier. Most player have a basic "now playing" playlist that temporarily stores all the songs that I selected for playback. If I select one song from the Song list view, it would add the current song and all the other songs to the "now playing" list. I know you said, you didn't wanna make a "now playing" screen or another "now playing" window, but it has become a necessity. Even most basic and simple player have a now playing view to house a "now playing" list. I case you want to take another look at that issue. Here it is: #19

**Comment by worldofpeace** [comment]
>I would like to play all the songs in my library with a click of the play button
>
That sounds like shuffle.

>Most player have a basic "now playing" playlist that temporarily stores all the songs that I selected for playback.
>
The default music app has features like this. It makes a queue playlist and a music history playlist if I'm not mistaken.

**Comment by SubhadeepJasu** [comment]
Shuffle in media players is only meant to play songs in the current playlist in random order. The shuffle button in most media players only determines whether too play the songs randomly or in the order they have been added. 

Not only the default music app but almost every popular media player maintains a temporary now play list. 

To make things simple you may not have to make a separate song list view. You can keep an "All artists" entry in the artist view itself. This will serve the same purpose. This entry will have all the songs found in the library. And you may keep it as the last entry in the view. In the same way you can keep an "All albums" entry in the albums view, its your choice.

As for the now playing screen, you don't have to make a separate window for it. You can make a new view called "now playing". It can two sections, one section would show the name of the currently playing song in big letters and the album and artist of that song. You can change the background of that section to a blurred out album art of the song. The second section which is on the same view would show a list of songs that are selected for playback, the user can remove songs from the list by hitting a cross icon on the list item, clicking on the list item would play the song instantly. And users can add songs to this list by clicking on a queue button on the song in artist and album view.

I am actually a big music lover and now playing is one of the features I use most of the time where I can add songs to the list and remove songs from the list and even rearrange songs in the list all while the songs are played real time. Coming from windows platform, this was a welcome feature windows media player, which I unfortunately miss in this app and its often kind of annoying.

**Comment by SubhadeepJasu** [comment]
The now playing window I talked about is the same thing as #40 (only that he is suggesting an ability to go full-screen). The ability to add songs to "now playing" list is kind of the same as #39 . Also the ability to hit the play button (when the now playing list is empty) and this will add all the songs to now playing list and automatically start playing them is similar to the one in the picture. I hate referencing other apps, but I got no choice.
![image](https://user-images.githubusercontent.com/20795161/32990453-8b7d48d0-cd4f-11e7-9a9c-f0b0ac84724c.png)

**Comment by worldofpeace** [comment]
@SubhadeepJasu I appreciate your efforts to communicate your point. I would like to point out that I can be hard for a dev to get to every feature request that you want. Keep in mind that they have their own vision in mind as well. 

If you want a dev to add a feature think in small manageable pieces that they can work on for now, keeping in mind the larger feature you would like them to create. 

I understand how you feel that this is related but one step at a time.

**Comment by SubhadeepJasu** [comment]
No hurries. Its okay. I am not gonna say like "Hey I want it done NOW" cause I am a dev too. I understand what it takes to build features in to apps. What I explained in the previous comments was how it could be implemented in a way if it was implemented. So I would suggest you take it easy. There are no deadlines. And if you have a vision which is better than the one I said you, I would be more than okay with it. Also, relax its open source, you sounded like you were over complicating it. Its just a feature request not an order. What I want to say is, its an idea, and it is meant to be kept alive. Not that its a dumb idea. So I would be happy if this feature is implemented at a later time, no big deal. I have nothing it gain from this app apart from the fact that I want it to get better. And once I learn some more of elementary OS development I would be able to help you guys or contribute the feature myself.

**Comment by SubhadeepJasu** [comment]
@worldofpeace You guys are in fact doing just what I wanted. I just saw the front page. That 
![image](https://user-images.githubusercontent.com/20795161/32993577-43aa691c-cd80-11e7-98b2-422fcd69bd59.png)
is exactly what I was talking about. Thanks a lot dudes. As I told you, if you do it any time, I would be more than happy and I mean it.

**Comment by yeboahnanaosei** [comment]
But @artemanufrij  are you not going to say anything about this? I don't know but this is such a basic feature in music players. At least say something. It's unfortunate but I've had to uninstall this app (I don't mean to discredit all your effort). I just find it very frustrating that I can't view all my songs in one list.

Just say something. Is it that you find it difficult? or you just don't have such intentions for the app.
I mean say something to us!!

**Comment by artemanufrij** [comment]
hey @yeboahnanaosei didn't got a lot of feedback for a list view. No, it's not difficult to implement it. I will check this feature after I have finished "external device support" for https://github.com/artemanufrij/showmypictures

**Comment by yeboahnanaosei** [comment]
You finally responded. Thank you. I don't really understand why you need a "lot of feedback" to implement such a basic feature in music players. Forgive me if I don't sound polite. I'm just surprised. 

elementary's music player, Noise, shows you all the songs in your library the moment you load them. With VLC you see a list of all the songs in the playlist by default you can later change it to whichever view you want. Clementine does this by default; it shows you a list of all your songs in your library not album view etc.. the list goes on. I mean we've come to expect music players to show us a list of all the songs in our library by default not a view of albums. It's fundamental. I'm just surprised bro, that this didn't come with the first release.

All right I'm shutting my mouth here. Thank you that you responded. I've seen that you self assigned this. All the best. Thanks for all your labor tho'.

**Comment by artemanufrij** [comment]
@yeboahnanaosei if I'm honest with you, I never used the list view in all the player I ever used. My focus was a clean album view and online radio stuff.

**Comment by yeboahnanaosei** [comment]
That's fine but @artemanufrij just try out about 10 music players and I can bet you that 90% of them will present you with a list of all songs by default instead of an album view.

Sincerely, it's not about your preference as a developer. It's all about the user. And trust me we've come to expect music players to show a list of all songs by default. You may have your preference but software has to be familiar. Thanks again.

**Comment by artemanufrij** [comment]
@yeboahnanaosei check this out:
![bildschirmfoto von 2018-02-18 16 18 50](https://user-images.githubusercontent.com/16517095/36353492-72620524-14c7-11e8-96c3-160cc383b972.png)

**Comment by SubhadeepJasu** [comment]
Nice! @artemanufrij Does that banner show the currently playing song or the currently selected song?

**Comment by artemanufrij** [comment]
@SubhadeepJasu current playing

**Comment by SubhadeepJasu** [comment]
Awesome!

**Comment by yeboahnanaosei** [comment]
@artemanufrij Hey, I'm rather seeing this late. I just tested it and it and everything seems to be working fine.

One tiny bit of suggestion. I think it will more intuitive if you rearrange the columns and position the title of the track first, then perhaps the artist and the rest can follow. I think its more natural if the name or title of the track comes first.

**Comment by SubhadeepJasu** [comment]
I agree with that, I didn't notice it earlier. The Title of the song should be displayed in big letters, followed by Artist.

**Comment by artemanufrij** [comment]
something like that?
![bildschirmfoto von 2018-02-20 20 26 09](https://user-images.githubusercontent.com/16517095/36444717-638a55b8-167c-11e8-906d-fecae6ed4d2a.png)

**Comment by artemanufrij** [comment]
@yeboahnanaosei @SubhadeepJasu  something like that?


![bildschirmfoto von 2018-02-20 20 30 03](https://user-images.githubusercontent.com/16517095/36444975-09d00184-167d-11e8-8459-c1a2e8652b67.png)

**Comment by SubhadeepJasu** [comment]
No. Show the title in big letters instead of Artist. As for artist the background blur picture says it all. Or you can show the artist along side the album.
![image](https://user-images.githubusercontent.com/20795161/36498405-30b52a44-1764-11e8-9009-51dc29e6759a.png)

**Comment by artemanufrij** [comment]
@SubhadeepJasu next try :smile: 
![bildschirmfoto von 2018-02-21 20 17 16](https://user-images.githubusercontent.com/16517095/36500327-4f67e546-1744-11e8-9139-47f7bc1fe71c.png)

**Comment by yeboahnanaosei** [comment]
Its looking good @artemanufrij :+1: 
I think ultimately, you will need to make it possible for the user to drag and rearrange the columns to his/her preference. And also make it possible for the user to select which columns he or she wants to have displayed. I think that will be really cool

**Comment by SubhadeepJasu** [comment]
@artemanufrij  Perfect!

**Comment by artemanufrij** [comment]
guys, I'm going to close this issue. for new FR or issues just open a new one :+1:
