### ISSUE TITLE
Repeat current song

### ISSUE THREAD

**Issue by yeboahnanaosei** [artemanufrij/playmymusic#45]
I think it will be nice to set repeat to play the current track. At the moment to repeat just one track I need to create a playlist of just that song, which I think is too much work.

**Comment by artemanufrij** [comment]
@yeboahnanaosei  could you test current master branch please?

![bildschirmfoto von 2017-11-18 11 34 19](https://user-images.githubusercontent.com/16517095/32979385-8da7c5b4-cc54-11e7-908f-152d33df51b9.png)

**Comment by yeboahnanaosei** [comment]
Can I test it by installing it from the AppCenter or I need to clone the repository and install?

**Comment by artemanufrij** [comment]
@yeboahnanaosei 

clone and install (impotant) ... after your test I will push it into appcenter

**Comment by yeboahnanaosei** [comment]
Ok. I'm installing the elementary-sdk but there seems to be an issue. I will let you know the moment I've installed and tested it

**Comment by yeboahnanaosei** [comment]
Tested and it works so far! :+1:

**Comment by artemanufrij** [comment]
@yeboahnanaosei thank you!

**Comment by yeboahnanaosei** [comment]
One last thing. How do I uninstall
