### ISSUE TITLE
Will there be Russian language? + question for dark theme!

### ISSUE THREAD

**Issue by Pashaonesided** [artemanufrij/playmymusic#46]
I'd love to see the Russian language!
And there is a problem with the dark theme EOS,the player understands it and converts the colors are not right. (White background ,white fonts, etc.) 
Thanks for the cool software for EOS!

**Comment by artemanufrij** [comment]
@Pashaonesided you can translit it in russian :smile: 

you can use http://poedit.net/ for translating it.
