### ISSUE TITLE
Sort Albums by album name only

### ISSUE THREAD

**Issue by BharatKalluri** [artemanufrij/playmymusic#47]
Awesome app, thanks for putting your effort into this! I am sorry if I am missing anything, but it the default album view sorts according to album_name/artist_name. It would be great it just sorts with the album name.

The reason I ask this is pretty simple. Suppose I download suicide squad Soundtrack. The app makes around 10 copies of suicide squad since all the songs sung in the movie are by different artists. It would be fantastic if we can change that!

**Comment by artemanufrij** [comment]
@BharatKalluri thank you for your feedback.

the problem is: if you have two albums with same title by two different artists in your lilbrary the app would show both albums like one album. I don't have a really clear solution for this issue and I don't know a music player with a good solution for collections.

In this case I use puddletag for fixing "ALBUM_ARTIST" tag in all music files of a collection.

**Comment by BharatKalluri** [comment]
@artemanufrij , thanks for the fast reply. Clementine has a sort option which only sorts according to album name. And does not even consider artist name. 
Anyways, thanks for the info. Please keep up the good work. If you feel this issue cannot be addressed,  Feel free to close this. I will give it a shot when I am free :)

**Comment by artemanufrij** [comment]
let me test clementine...

**Comment by rasmus91** [comment]
I find this to be an issue as well. Albums like '20 greatest rock hits' or some such just create a mess. I have a bunch of sound tracks and such, and this is incredibly annoying. Two albums by different artists having the same name, is rarer, i believe than one album with different artists, so perhaps the sorting should be changed to reflect this?

**Comment by artemanufrij** [comment]
ok guys,
what do you thing about three options for sorting content:
1) Artist - Year - Album (currently sorting)
2) Album - Artist
3) Artist -Album (ignore Year)

???

**Comment by artemanufrij** [comment]
you can test it in current master branch:
![screenshot von 2018-11-02 23 48 35](https://user-images.githubusercontent.com/16517095/47944260-bedaca00-defa-11e8-8485-ee8b2982cb59.png)

**Comment by artemanufrij** [comment]
Released

**Comment by rasmus91** [comment]
Sorry for the late reply (SO busy these days)

That sorting does not solve the problem. What is needed, would be something like:

Sorting -> Album

Might be

Sorting -> Album - Year

would also work, though I'm not certain, as the Song might've been released on a different year than the rest of the songs in the Album (Such as if it's a platinum collection or whatever)

**Comment by artemanufrij** [comment]
@rasmus91 have you tried it? I guess `Album - Artist` have bahaviour you need.

**Comment by rasmus91** [comment]
Yes, i have tried it. It leaves me looking at this:

![skaermbillede fra 2018-11-09 11-02-16](https://user-images.githubusercontent.com/2297739/48256225-3cc53680-e40f-11e8-886c-7b5f3507cd63.png)

**Comment by artemanufrij** [comment]
I think to sort only by album will have similar result
