### ISSUE TITLE
Song titles color with elementary dark

### ISSUE THREAD

**Issue by popvladaurel** [artemanufrij/playmymusic#48]
When using the elementary dark theme, song titles are unreadable in Artists View.
![screenshot from 2017-11-17 19 37 28](https://user-images.githubusercontent.com/23455688/32960753-c9a9ebc2-cbce-11e7-9539-d61f12062157.png)

**Comment by artemanufrij** [comment]
Fixed:
![bildschirmfoto von 2017-11-17 19 33 00](https://user-images.githubusercontent.com/16517095/32962980-c0087c28-cbce-11e7-8f21-d405c7aa1a14.png)
