### ISSUE TITLE
[Enhancement] Artist image and artist info from WEB

### ISSUE THREAD

**Issue by varlesh** [artemanufrij/playmymusic#50]
Will be cool use Artist image and info from any music service (MusicBrainz, Wikimedia, LastFM, etc)...
Example mockup:
![2017-11-19 01 25 44](https://user-images.githubusercontent.com/8083855/32985027-623458d6-ccca-11e7-8721-4a95cf41c6f2.png)
Artist info with scrolled widget - it's very good for long text.

**Comment by artemanufrij** [comment]
for artist image you can enable it here.
![bildschirmfoto von 2017-11-18 22 48 08](https://user-images.githubusercontent.com/16517095/32985088-9b5abeba-ccb2-11e7-9d6c-cbf4322dffa9.png)

or you can put a image into you folder named: `aritst.jpg`

**Comment by varlesh** [comment]
> for artist image you can enable it here.

Enabled, but not worked.
On LOG i see this:
```
** (com.github.artemanufrij.playmymusic:25157): WARNING **: TagManager.vala:63: DISCOVER ERROR: '3' Resource not found. GST_DISCOVERER_ERROR
```
> or you can put a image into you folder named: aritst.jpg

Very good... But think about get  info from any web service (if possible)... It's good looking

**Comment by artemanufrij** [comment]
it a ID3 warning. it will be fired if ID3 tag can't be read from a music file.

**Comment by artemanufrij** [comment]
@varlesh could you check if artists you have exists on MusicBrainz...

**Comment by varlesh** [comment]
Thirty Seconds to Mars > https://musicbrainz.org/artist/d8354b38-e942-4c89-ba93-29323432abc3
![2017-11-19 02-11-35](https://user-images.githubusercontent.com/8083855/32985209-01e51f60-cccf-11e7-9949-1065e8b066e5.png)
mediainfo example:
```
mediainfo 01*mp3
General
Complete name                            : 01.Kings And Queens.mp3
Format                                   : MPEG Audio
File size                                : 13.8 MiB
Duration                                 : 5mn 44s
Overall bit rate mode                    : Constant
Overall bit rate                         : 320 Kbps
Album                                    : Greatest Hits (CD1)
Album/Performer                          : Thirty Seconds To Mars
Track name                               : Kings And Queens
Track name/Position                      : 01
Performer                                : Thirty Seconds To Mars
Encoded by                               : Dash.G.F.
Genre                                    : Alternative Rock, Hard Rock
Recorded date                            : 2011
Writing library                          : LAME3.98r
Cover                                    : Yes
Cover type                               : Cover (front)
Cover MIME                               : image/jpeg
Comment                                  :  

Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Mode                                     : Joint stereo
Duration                                 : 5mn 45s
Bit rate mode                            : Constant
Bit rate                                 : 320 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 13.2 MiB (95%)
Writing library                          : LAME3.98r
Encoding settings                        : -m j -V 4 -q 5 -lowpass 20.5

```

**Comment by artemanufrij** [comment]
but not `Greatest Hits (CD1)` if you put an album in your Library it will work. Artist + Album is unique

**Comment by varlesh** [comment]
@artemanufrij You right, worked :+1:  
Please think about artist info

**Comment by artemanufrij** [comment]
I'm going to close this issue "Artist Info" should be tracked in a separate issue...
