### ISSUE TITLE
Can't handle hashtags in folder and filenames, possibly also can't handle large music libraries

### ISSUE THREAD

**Issue by Zachs-Kappler** [artemanufrij/playmymusic#54]
Terminal Output:
```
** (com.github.artemanufrij.playmymusic:12763): WARNING **: LocalFilesManager.vala:85: Error opening directory '/home/daniel/Music/30 ': No such file or directory
** (com.github.artemanufrij.playmymusic:12763): WARNING **: LocalFilesManager.vala:85: Error opening directory '/home/zachs/Music/Kill Club ': No such file or directory
fish: “com.github.artemanufrij.playmym…” terminated by signal SIGSEGV (Address boundary error)
```

The folder's names are `30 #1 Hits (Google Play Bonus Track Version)` and `Kill Club #003`.

An address boundary error segfault occurs shortly after, either because of bad handling of special characters or because at this point it has discovered around 5000+ songs.

**Comment by artemanufrij** [comment]
hey @Zachs-Kappler, thank you for your feedback... I will try to fix it tonight.

**Comment by artemanufrij** [comment]
@Zachs-Kappler could you test current master branch please?

**Comment by Zachs-Kappler** [comment]
Okay, as of the newest version I'm not getting errors for those two folders, it added three albums, but it is still closing out during the initial library import with the same address boundary error.

Any idea what I could do to help narrow down what is wrong?

**Comment by artemanufrij** [comment]
@Zachs-Kappler  I need some informations:
* is your library mounted?
if yes: SMB/NFS/etc?

when crashes is? after how many files?

the problem is that I can't reproduce it on my system. I have > 6500 music files. I tested it with local files, smb-mounted, nfs-mounted.... And it works...

**Comment by Zachs-Kappler** [comment]
The folder it is searching through is a local Music folder in my home folder. My home folder is on a healthy drive. All of the files are either flac, ogg, or a plethora of chiptune formats that should be ignored.

Right now, it is acting differently. Originally, it crashed after finding one song in three albums and subsequent launches added nothing else. After trying to get it to stop scanning on startup, it is now continuing to dig through my music collection successfully. The folder obeys the filename limitations Windows has on what characters can be used.

On the most recent launch, I got the following twice:
```
(com.github.artemanufrij.playmymusic:27355): Gtk-WARNING **: Failed to set text '<b>> album title goes here <</b>' from markup due to error parsing markup: Error on line 1 char 39: '<' is not a valid name
```
After that, I get the following error occasionally as `ARTIST ID` lines go by:
```
(com.github.artemanufrij.playmymusic:27355): GVFS-WARNING **: can't init metadata tree /home/daniel/.local/share/gvfs-metadata/home: open: Permission denied
```

It seems to be working now, so I guess this issue can be closed and I'll open a new one if something else happens.
