### ISSUE TITLE
Get song name from internet radio stream

### ISSUE THREAD

**Issue by J0Ar** [artemanufrij/playmymusic#58]
Hey Artem :) 
Is it possible to get the song name of the current played song in the header bar of Music Player and also in wingpanel-indicator-sound? At the moment it just shows the name of the radio station. 

THX JAr :)

_by the way...i paypal'd you because of all your apps ;)_

**Comment by artemanufrij** [comment]
@J0Ar Thank you for your Feedback and for your Support... :smile: 

I will check it it's possible to grab the song name...

**Comment by artemanufrij** [comment]
@J0Ar It works, but could't grab the information in all radio stations I use.
![bildschirmfoto von 2017-12-31 15 44 53](https://user-images.githubusercontent.com/16517095/34462368-c0daad10-ee42-11e7-901b-fe60b3e368ef.png)

**Comment by artemanufrij** [comment]
fixed in #6f5d775

**Comment by riker09** [comment]
I'm listening to soma.fm mostly. I've added the AAC playlist, eg. http://somafm.com/groovesalad130.pls but I don't see the current title. I've tried their other URLs:

MP3 256kb

* Main PLS: http://somafm.com/groovesalad256.pls
* Main M3U: http://somafm.com/m3u/groovesalad256.m3u
* Direct Server: http://ice1.somafm.com/groovesalad-256-mp3

AAC 128kb

* Main PLS: http://somafm.com/groovesalad130.pls
* Main M3U: http://somafm.com/m3u/groovesalad130.m3u
* Direct Server: http://ice1.somafm.com/groovesalad-128-aac

None of them show the current track and artist. I know that this works with other players like radiotray. I'm not sure if there is such thing as a standard on titles in radio streams and maybe soma.fm just doesn't stick to that standard?
