### ISSUE TITLE
Integrate control of media in sound indicator

### ISSUE THREAD

**Issue by worldofpeace** [artemanufrij/playmymusic#6]
Some function as the default music app.

**Comment by dmanlfc** [comment]
Agreed - would be great

**Comment by SubhadeepJasu** [comment]
Also showing the album artwork in the sound indicator.

**Comment by SubhadeepJasu** [comment]
notification for song change in playlist.

**Comment by SubhadeepJasu** [comment]
The two issues are different.

**Comment by artemanufrij** [comment]
![bildschirmfoto von 2017-10-09 20 25 22](https://user-images.githubusercontent.com/16517095/31352762-43bd51a0-ad30-11e7-9c34-a63e874e325b.png)

**Comment by SubhadeepJasu** [comment]
Yeah this thing. Should be good. Nice!

**Comment by artemanufrij** [comment]
sound indicator was shipped. New release is waiting for testing.

**Comment by SubhadeepJasu** [comment]
ok
