### ISSUE TITLE
Icon is blurry in AppCenter

### ISSUE THREAD

**Issue by jtrees** [artemanufrij/playmymusic#64]
In AppCenter the icon is blurry because a 128x128 version is missing.

![screenshot](https://preview.ibb.co/bJQiW6/Screenshot_from_2018_01_30_09_15_35.png)

**Comment by artemanufrij** [comment]
Hey @jtrees it's not an app issue. graphui has a 128px icon:
![bildschirmfoto von 2018-02-14 23 35 39](https://user-images.githubusercontent.com/16517095/36231828-cd3b9c7a-11df-11e8-8550-1187297b24cc.png)

**Comment by artemanufrij** [comment]
I'm going to close this issue because it's a appstream bug
