### ISSUE TITLE
[Enhancement] Integrate control of media in Plank icon secondary click

### ISSUE THREAD

**Issue by LunkRat** [artemanufrij/playmymusic#65]
For example a right-click on the Plank launcher for [Lollypop](https://wiki.gnome.org/action/show/Lollypop) shows media controls:

![Lollypop plank media controls](https://user-images.githubusercontent.com/1657096/35645436-69b26c5a-0691-11e8-9d33-005b57480760.png)

Would be a nice addition for richer elementaryOS integration. 

I love your player.

**Comment by artemanufrij** [comment]
@LunkRat cool idea! Will implement it next weekend :+1:

**Comment by artemanufrij** [comment]
@LunkRat could you test current master branch please?

![bildschirmfoto von 2018-02-03 00 56 09](https://user-images.githubusercontent.com/16517095/35759936-1c530aa8-087d-11e8-9ef8-b98013a2d48c.png)

**Comment by artemanufrij** [comment]
media keys were released…

**Comment by LunkRat** [comment]
I tested and it works perfectly. Very nice enhancement. Thank you @artemanufrij for the quick commits!

**Comment by artemanufrij** [comment]
@LunkRat you are welcome :smile:
