### ISSUE TITLE
[Feature Request] New Tab: Songs

### ISSUE THREAD

**Issue by btd1337** [artemanufrij/playmymusic#74]
Create a new tab: Songs.

This tab will display the entire list of songs in the user's library.

![new tab](https://user-images.githubusercontent.com/11943860/36164554-d3a7df54-10d3-11e8-8357-e7c4101a42d7.jpeg)

**Comment by SubhadeepJasu** [comment]
Done in current version. Its called List View.

**Comment by artemanufrij** [comment]
Ok... then I'm going to close this issue!

Have a nice day :smile:
