### ISSUE TITLE
DLNA On Play Music

### ISSUE THREAD

**Issue by torikulhabib** [artemanufrij/playmymusic#77]
There is Option just read with Smartphone.
![screenshot from 2018-02-16 11 24 59](https://user-images.githubusercontent.com/26135527/36293584-75ac46c4-130d-11e8-89c1-a017df5c621a.png)
![screenshot_2018-02-16-11-27-36](https://user-images.githubusercontent.com/26135527/36293593-84ef43c0-130d-11e8-81cc-30bdd1ce6b74.jpg)
![screenshot_2018-02-16-11-27-44](https://user-images.githubusercontent.com/26135527/36293648-edea3f42-130d-11e8-885b-2f5b38f6c67c.jpg)

I Hope DLNA share can read in Play music and from dlna pc elementary os and anything from dlna connection

![screenshot_2018-02-16-11-29-40](https://user-images.githubusercontent.com/26135527/36293622-b5761104-130d-11e8-918e-1e8fb2bd0b0d.jpg)

**Comment by artemanufrij** [comment]
@torikulhabib I had already a prototype for DLNA recipient :thinking: I will take a look in my code archive

**Comment by torikulhabib** [comment]
i was succes make DLNA on my project.
https://github.com/torikulhabib/niki
