### ISSUE TITLE
Shuffle and Repeat buttons not available in list view.

### ISSUE THREAD

**Issue by SubhadeepJasu** [artemanufrij/playmymusic#82]
The title says it all. Its in v0.6.1. Ignore if already fixed.

**Comment by artemanufrij** [comment]
hey @SubhadeepJasu could you test current master branch please?

**Comment by SubhadeepJasu** [comment]
Ok.

**Comment by SubhadeepJasu** [comment]
Working! Thanks for the fix.

**Comment by SubhadeepJasu** [comment]
![screenshot from 2018-03-03 13-48-35](https://user-images.githubusercontent.com/20795161/36932067-b5922dd4-1ee9-11e8-9528-f6cfa17f9d45.png)

**Comment by artemanufrij** [comment]
Thanks for feedback @SubhadeepJasu  :+1:
