### ISSUE TITLE
Album and Artist data of some songs are not being displayed in Tracks view.

### ISSUE THREAD

**Issue by SubhadeepJasu** [artemanufrij/playmymusic#97]
In the Track View's now-playing pane (not sure what to call it). The album and artist info of particular songs are not being displayed. Now the here's the catch, this only happens with songs from "Above & Beyond". I don't know but I speculate it could due to the presence of '&' symbol in the artist name. Also if I change to another song from a different artist and change back to a song from A&B, then the album and artist of the previous song is displayed.

This one shows when I first play a music from A&B right after starting melody.
![image](https://user-images.githubusercontent.com/20795161/37866072-5220b626-2fab-11e8-951e-ada7c3f0a08b.png)

This one shows what happens when I switch to another song (in this case "Float Away") and switch back to "Thing called Love". It shows the artist data of "Float Away" instead of "Thing called Love".
![image](https://user-images.githubusercontent.com/20795161/37866090-a6fda758-2fab-11e8-9577-5e50e21e21a6.png)

**Comment by artemanufrij** [comment]
@SubhadeepJasu let me check it :thinking:

**Comment by artemanufrij** [comment]
@SubhadeepJasu fixed in master branch :+1:

**Comment by artemanufrij** [comment]
![bildschirmfoto von 2018-03-24 17 16 56](https://user-images.githubusercontent.com/16517095/37866174-33352f9a-2f87-11e8-8f8a-59c61efa801c.png)

**Comment by SubhadeepJasu** [comment]
Thanks! :)
